/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;
import swing.ColorPallete;

/**
 *
 * @author AG SETO GALIH D
 */
public class LoginRegisterView extends javax.swing.JFrame {

    /** Creates new form LoginRegisterView */
    private CardLayout cardLayout;
    private static ColorPallete cp = new ColorPallete();
    private static final String emptyString = "";

    public LoginRegisterView() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));

        loginHere.setCursor(new Cursor(Cursor.HAND_CURSOR));
        registerHere.setCursor(new Cursor(Cursor.HAND_CURSOR));

        showPassLogin.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                if (showPassLogin.isSelected()) {
                    inputPasswordLogin.setEchoChar((char) 0);
                    // do something if check box is selected
                } else {
                    inputPasswordLogin.setEchoChar((char) 8226);
                    // check box is unselected, do something else
                }
            }
        });
        showPassRegister.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                if (showPassRegister.isSelected()) {
                    inputPasswordRegister.setEchoChar((char) 0);
                    // do something if check box is selected
                } else {
                    inputPasswordRegister.setEchoChar((char) 8226);
                    // check box is unselected, do something else
                }
            }
        });

        cardLayout = (CardLayout) cardLayoutPanel.getLayout();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardLayoutPanel = new javax.swing.JPanel();
        baseLoginPanel = new panel.LoginRegisterBasePanel();
        leftLoginPanel = new javax.swing.JPanel();
        loginTitle = new javax.swing.JLabel();
        registerHere = new javax.swing.JLabel();
        belumPunyaAkun = new javax.swing.JLabel();
        loginBtn = new swing.component.Button();
        textFieldLoginPanel = new javax.swing.JPanel();
        inputUsernameLogin = new swing.component.TextField();
        inputPasswordLogin = new swing.component.PasswordField();
        showPassLogin = new javax.swing.JCheckBox();
        rightLoginPanel = new swing.GradientPanelRight();
        illustration = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        btnCloseLogin = new swing.component.ButtonOutLine();
        baseRegisterPanel = new panel.LoginRegisterBasePanel();
        leftRegisterPanel = new javax.swing.JPanel();
        registerTitle = new javax.swing.JLabel();
        loginHere = new javax.swing.JLabel();
        sudahPunyaAkun = new javax.swing.JLabel();
        registerBtn = new swing.component.Button();
        textFieldRegisterPanel = new javax.swing.JPanel();
        showPassRegister = new javax.swing.JCheckBox();
        inputUsernameRegister = new swing.component.TextField();
        inputNamaRegister = new swing.component.TextField();
        inputNoTelpRegister = new swing.component.TextField();
        inputAlamatRegister = new swing.component.TextField();
        inputPasswordRegister = new swing.component.PasswordField();
        rightRegisterPanel = new swing.GradientPanelRight();
        illustration1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        slogan1 = new javax.swing.JLabel();
        btnCloseRegister = new swing.component.ButtonOutLine();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        cardLayoutPanel.setOpaque(false);
        cardLayoutPanel.setLayout(new java.awt.CardLayout());

        leftLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftLoginPanel.setOpaque(false);

        loginTitle.setBackground(new java.awt.Color(0, 0, 0));
        loginTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(0, 153, 0));
        loginTitle.setText("Login");

        registerHere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerHere.setForeground(new java.awt.Color(0, 153, 0));
        registerHere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerHere.setText("Register");
        registerHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerHereMouseClicked(evt);
            }
        });

        belumPunyaAkun.setForeground(new java.awt.Color(0, 0, 0));
        belumPunyaAkun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        belumPunyaAkun.setText("Belum punya akun?");

        loginBtn.setText("Login");
        loginBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textFieldLoginPanel.setOpaque(false);
        textFieldLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputUsernameLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputUsernameLogin.setLabelText("Username");
        textFieldLoginPanel.add(inputUsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, -1));

        inputPasswordLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputPasswordLogin.setLabelText("Password");
        textFieldLoginPanel.add(inputPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, -1));

        showPassLogin.setForeground(cp.getColor(1)
        );
        showPassLogin.setText("Show Password");
        showPassLogin.setBorder(null);
        showPassLogin.setContentAreaFilled(false);
        showPassLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassLogin.setFocusPainted(false);
        showPassLogin.setFocusable(false);
        showPassLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textFieldLoginPanel.add(showPassLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        javax.swing.GroupLayout leftLoginPanelLayout = new javax.swing.GroupLayout(leftLoginPanel);
        leftLoginPanel.setLayout(leftLoginPanelLayout);
        leftLoginPanelLayout.setHorizontalGroup(
            leftLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLoginPanelLayout.createSequentialGroup()
                .addGroup(leftLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftLoginPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(leftLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leftLoginPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(belumPunyaAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(registerHere, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        leftLoginPanelLayout.setVerticalGroup(
            leftLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLoginPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(belumPunyaAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerHere, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        illustration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        illustration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/illustration/—Pngtree—medical doctor pharmacy illustration vector_4384152.png"))); // NOI18N

        title.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Apotek Tumbuh Bersama");

        slogan.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        slogan.setForeground(new java.awt.Color(255, 255, 255));
        slogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slogan.setText("Pelopor Utama Sehat Jiwa Raga");

        btnCloseLogin.setText("X");
        btnCloseLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightLoginPanelLayout = new javax.swing.GroupLayout(rightLoginPanel);
        rightLoginPanel.setLayout(rightLoginPanelLayout);
        rightLoginPanelLayout.setHorizontalGroup(
            rightLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLoginPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(rightLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slogan, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(illustration, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        rightLoginPanelLayout.setVerticalGroup(
            rightLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLoginPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCloseLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(slogan)
                .addGap(48, 48, 48)
                .addComponent(illustration, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout baseLoginPanelLayout = new javax.swing.GroupLayout(baseLoginPanel);
        baseLoginPanel.setLayout(baseLoginPanelLayout);
        baseLoginPanelLayout.setHorizontalGroup(
            baseLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLoginPanelLayout.createSequentialGroup()
                .addComponent(leftLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        baseLoginPanelLayout.setVerticalGroup(
            baseLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cardLayoutPanel.add(baseLoginPanel, "layoutLogin");

        leftRegisterPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftRegisterPanel.setOpaque(false);

        registerTitle.setBackground(new java.awt.Color(0, 0, 0));
        registerTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        registerTitle.setForeground(new java.awt.Color(0, 153, 0));
        registerTitle.setText("Register");

        loginHere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginHere.setForeground(new java.awt.Color(0, 153, 0));
        loginHere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginHere.setText("Login");
        loginHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginHereMouseClicked(evt);
            }
        });

        sudahPunyaAkun.setForeground(new java.awt.Color(0, 0, 0));
        sudahPunyaAkun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sudahPunyaAkun.setText("Sudah punya akun?");

        registerBtn.setText("Register");
        registerBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textFieldRegisterPanel.setOpaque(false);
        textFieldRegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showPassRegister.setForeground(cp.getColor(1)
        );
        showPassRegister.setText("Show Password");
        showPassRegister.setBorder(null);
        showPassRegister.setContentAreaFilled(false);
        showPassRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassRegister.setFocusPainted(false);
        showPassRegister.setFocusable(false);
        showPassRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textFieldRegisterPanel.add(showPassRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        inputUsernameRegister.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputUsernameRegister.setLabelText("Username");
        textFieldRegisterPanel.add(inputUsernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, -1));

        inputNamaRegister.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputNamaRegister.setLabelText("Nama Lengkap");
        textFieldRegisterPanel.add(inputNamaRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, -1));

        inputNoTelpRegister.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputNoTelpRegister.setLabelText("Nomor Telepon");
        textFieldRegisterPanel.add(inputNoTelpRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, -1));

        inputAlamatRegister.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputAlamatRegister.setLabelText("Alamat");
        textFieldRegisterPanel.add(inputAlamatRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, -1));

        inputPasswordRegister.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputPasswordRegister.setLabelText("Password");
        textFieldRegisterPanel.add(inputPasswordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, -1));

        javax.swing.GroupLayout leftRegisterPanelLayout = new javax.swing.GroupLayout(leftRegisterPanel);
        leftRegisterPanel.setLayout(leftRegisterPanelLayout);
        leftRegisterPanelLayout.setHorizontalGroup(
            leftRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftRegisterPanelLayout.createSequentialGroup()
                .addGroup(leftRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftRegisterPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(leftRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leftRegisterPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(sudahPunyaAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(loginHere, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        leftRegisterPanelLayout.setVerticalGroup(
            leftRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftRegisterPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(registerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sudahPunyaAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginHere, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        illustration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        illustration1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/illustration/—Pngtree—medical doctor pharmacy illustration vector_4384152.png"))); // NOI18N

        title1.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Apotek Tumbuh Bersama");

        slogan1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        slogan1.setForeground(new java.awt.Color(255, 255, 255));
        slogan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slogan1.setText("Pelopor Utama Sehat Jiwa Raga");

        btnCloseRegister.setText("X");
        btnCloseRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightRegisterPanelLayout = new javax.swing.GroupLayout(rightRegisterPanel);
        rightRegisterPanel.setLayout(rightRegisterPanelLayout);
        rightRegisterPanelLayout.setHorizontalGroup(
            rightRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightRegisterPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(rightRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slogan1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(illustration1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightRegisterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        rightRegisterPanelLayout.setVerticalGroup(
            rightRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightRegisterPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCloseRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(slogan1)
                .addGap(48, 48, 48)
                .addComponent(illustration1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout baseRegisterPanelLayout = new javax.swing.GroupLayout(baseRegisterPanel);
        baseRegisterPanel.setLayout(baseRegisterPanelLayout);
        baseRegisterPanelLayout.setHorizontalGroup(
            baseRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseRegisterPanelLayout.createSequentialGroup()
                .addComponent(leftRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        baseRegisterPanelLayout.setVerticalGroup(
            baseRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cardLayoutPanel.add(baseRegisterPanel, "layoutRegister");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cardLayoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cardLayoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearLoginComponents() {
        inputUsernameLogin.setText(emptyString);
        inputPasswordLogin.setText(emptyString);
        showPassLogin.setSelected(false);
    }

    private void clearRegisterComponents() {
        inputUsernameRegister.setText(emptyString);
        inputNamaRegister.setText(emptyString);
        inputNoTelpRegister.setText(emptyString);
        inputAlamatRegister.setText(emptyString);
        inputPasswordRegister.setText(emptyString);
        showPassRegister.setSelected(false);
    }

    private void registerHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerHereMouseClicked
        // TODO add your handling code here:
        clearLoginComponents();
        cardLayout.show(cardLayoutPanel, "layoutRegister");
    }//GEN-LAST:event_registerHereMouseClicked

    private void loginHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHereMouseClicked
        // TODO add your handling code here:
        clearRegisterComponents();
        cardLayout.show(cardLayoutPanel, "layoutLogin");
    }//GEN-LAST:event_loginHereMouseClicked

    private void btnCloseLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseLoginActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseLoginActionPerformed

    private void btnCloseRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseRegisterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panel.LoginRegisterBasePanel baseLoginPanel;
    private panel.LoginRegisterBasePanel baseRegisterPanel;
    private javax.swing.JLabel belumPunyaAkun;
    private swing.component.ButtonOutLine btnCloseLogin;
    private swing.component.ButtonOutLine btnCloseRegister;
    private javax.swing.JPanel cardLayoutPanel;
    private javax.swing.JLabel illustration;
    private javax.swing.JLabel illustration1;
    private swing.component.TextField inputAlamatRegister;
    private swing.component.TextField inputNamaRegister;
    private swing.component.TextField inputNoTelpRegister;
    private swing.component.PasswordField inputPasswordLogin;
    private swing.component.PasswordField inputPasswordRegister;
    private swing.component.TextField inputUsernameLogin;
    private swing.component.TextField inputUsernameRegister;
    private javax.swing.JPanel leftLoginPanel;
    private javax.swing.JPanel leftRegisterPanel;
    private swing.component.Button loginBtn;
    private javax.swing.JLabel loginHere;
    private javax.swing.JLabel loginTitle;
    private swing.component.Button registerBtn;
    private javax.swing.JLabel registerHere;
    private javax.swing.JLabel registerTitle;
    private swing.GradientPanelRight rightLoginPanel;
    private swing.GradientPanelRight rightRegisterPanel;
    private javax.swing.JCheckBox showPassLogin;
    private javax.swing.JCheckBox showPassRegister;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel slogan1;
    private javax.swing.JLabel sudahPunyaAkun;
    private javax.swing.JPanel textFieldLoginPanel;
    private javax.swing.JPanel textFieldRegisterPanel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
