/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author AG SETO GALIH D
 */
public class GradientPanelLeft extends javax.swing.JPanel {

    private static ColorPallete colorPallete = new ColorPallete();

    /** Creates new form GradientPanel */
    public GradientPanelLeft() {
        initComponents();
        //agar panel menjadi transaparan di settingan background colornya
        //supaya dapat ditimpa/dioverride dengan warna gradient buatan sendiri
        setOpaque(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //mengoverride background color panel
    //dengan warna gradient buatan sendiri
    @Override
    protected void paintComponent(Graphics g) {

        //mendefine variabel warna gradient
        Color color1 = colorPallete.getColor(0);
        Color color2 = colorPallete.getColor(1);

        //mendefine variabel width dan height panel
        int width = getWidth();
        int height = getHeight();

        Graphics2D g2 = (Graphics2D) g;

        //memberi efek antialiasing pada gradient yang akan dibuat
        //agar transisi warna gradient lebih smooth
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        //membuat objek GradientPaint dan mengeset warna gradient ke panel
        GradientPaint gradientPaint = new GradientPaint(0, 0, color1, 0, height, color2);
        g2.setPaint(gradientPaint);

        //untuk memberi border radius
        //parameter: startX, startY, endX, endY, borderArcWidth, borderArcHeight
        int borderRadius = 50;
        g2.fillRoundRect(0, 0, width, height, borderRadius, borderRadius);

        //menghapus border radius sebelah kanan dengan membuat rectangle baru yang menutupi
        //parameter: startX, startY, endX, endY
        //g2.fillRect(width - 105, 0, width, height);
        g2.fillRect(width, 0, width - 105, height);

//        g2.dispose();
//        super.paintComponent(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
