/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.backup;

/**
 *
 * @author AG SETO GALIH D
 */
public class LRViewTabbedPaneBackup extends javax.swing.JFrame {

    /** Creates new form LRViewTabbedPaneBackup */
    public LRViewTabbedPaneBackup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane1 = new javax.swing.JTabbedPane();
        baseLoginPanel1 = new panel.LoginRegisterBasePanel();
        leftLoginPanel1 = new javax.swing.JPanel();
        loginTitle1 = new javax.swing.JLabel();
        registerHere1 = new javax.swing.JLabel();
        belumPunyaAkun1 = new javax.swing.JLabel();
        loginBtn1 = new swing.component.Button();
        textFieldLoginPanel1 = new javax.swing.JPanel();
        inputUsernameLogin1 = new swing.component.TextField();
        inputPasswordLogin1 = new swing.component.PasswordField();
        rightLoginPanel1 = new swing.GradientPanelRight();
        illustration2 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        slogan2 = new javax.swing.JLabel();
        baseRegisterPanel1 = new panel.LoginRegisterBasePanel();
        leftRegisterPanel1 = new javax.swing.JPanel();
        registerTitle1 = new javax.swing.JLabel();
        loginHere1 = new javax.swing.JLabel();
        sudahPunyaAkun1 = new javax.swing.JLabel();
        registerBtn1 = new swing.component.Button();
        textFieldRegisterPanel1 = new javax.swing.JPanel();
        inputUsernameRegister1 = new swing.component.TextField();
        inputPasswordRegister1 = new swing.component.PasswordField();
        inputNamaRegister1 = new swing.component.TextField();
        inputNoTelpRegister1 = new swing.component.TextField();
        inputAlamatRegister1 = new swing.component.TextField();
        rightRegisterPanel1 = new swing.GradientPanelRight();
        illustration3 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        slogan3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftLoginPanel1.setBackground(new java.awt.Color(255, 255, 255));
        leftLoginPanel1.setOpaque(false);

        loginTitle1.setBackground(new java.awt.Color(0, 0, 0));
        loginTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginTitle1.setForeground(new java.awt.Color(0, 153, 0));
        loginTitle1.setText("Login");

        registerHere1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerHere1.setForeground(new java.awt.Color(0, 153, 0));
        registerHere1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerHere1.setText("Register");
        registerHere1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerHere1MouseClicked(evt);
            }
        });

        belumPunyaAkun1.setForeground(new java.awt.Color(0, 0, 0));
        belumPunyaAkun1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        belumPunyaAkun1.setText("Belum punya akun?");

        loginBtn1.setText("Login");
        loginBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textFieldLoginPanel1.setOpaque(false);
        textFieldLoginPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputUsernameLogin1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputUsernameLogin1.setLabelText("Username");
        textFieldLoginPanel1.add(inputUsernameLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, -1));

        inputPasswordLogin1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputPasswordLogin1.setLabelText("Password");
        textFieldLoginPanel1.add(inputPasswordLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, -1));

        javax.swing.GroupLayout leftLoginPanel1Layout = new javax.swing.GroupLayout(leftLoginPanel1);
        leftLoginPanel1.setLayout(leftLoginPanel1Layout);
        leftLoginPanel1Layout.setHorizontalGroup(
            leftLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLoginPanel1Layout.createSequentialGroup()
                .addGroup(leftLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftLoginPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(leftLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldLoginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leftLoginPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(belumPunyaAkun1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(registerHere1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        leftLoginPanel1Layout.setVerticalGroup(
            leftLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLoginPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(loginTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldLoginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(belumPunyaAkun1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerHere1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        illustration2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        illustration2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/illustration/—Pngtree—medical doctor pharmacy illustration vector_4384152.png"))); // NOI18N

        title2.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 255));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Apotek Tumbuh Bersama");

        slogan2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        slogan2.setForeground(new java.awt.Color(255, 255, 255));
        slogan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slogan2.setText("Pelopor Utama Sehat Jiwa Raga");

        javax.swing.GroupLayout rightLoginPanel1Layout = new javax.swing.GroupLayout(rightLoginPanel1);
        rightLoginPanel1.setLayout(rightLoginPanel1Layout);
        rightLoginPanel1Layout.setHorizontalGroup(
            rightLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLoginPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(rightLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slogan2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(illustration2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        rightLoginPanel1Layout.setVerticalGroup(
            rightLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLoginPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(slogan2)
                .addGap(18, 48, Short.MAX_VALUE)
                .addComponent(illustration2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout baseLoginPanel1Layout = new javax.swing.GroupLayout(baseLoginPanel1);
        baseLoginPanel1.setLayout(baseLoginPanel1Layout);
        baseLoginPanel1Layout.setHorizontalGroup(
            baseLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLoginPanel1Layout.createSequentialGroup()
                .addComponent(leftLoginPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightLoginPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        baseLoginPanel1Layout.setVerticalGroup(
            baseLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftLoginPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightLoginPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane1.addTab("loginTab", baseLoginPanel1);

        leftRegisterPanel1.setBackground(new java.awt.Color(255, 255, 255));
        leftRegisterPanel1.setOpaque(false);

        registerTitle1.setBackground(new java.awt.Color(0, 0, 0));
        registerTitle1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        registerTitle1.setForeground(new java.awt.Color(0, 153, 0));
        registerTitle1.setText("Register");

        loginHere1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginHere1.setForeground(new java.awt.Color(0, 153, 0));
        loginHere1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginHere1.setText("Login");
        loginHere1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginHere1MouseClicked(evt);
            }
        });

        sudahPunyaAkun1.setForeground(new java.awt.Color(0, 0, 0));
        sudahPunyaAkun1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sudahPunyaAkun1.setText("Sudah punya akun?");

        registerBtn1.setText("Register");
        registerBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textFieldRegisterPanel1.setOpaque(false);
        textFieldRegisterPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputUsernameRegister1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputUsernameRegister1.setLabelText("Username");
        textFieldRegisterPanel1.add(inputUsernameRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, -1));

        inputPasswordRegister1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputPasswordRegister1.setLabelText("Password");
        textFieldRegisterPanel1.add(inputPasswordRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, -1));

        inputNamaRegister1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputNamaRegister1.setLabelText("Nama Lengkap");
        textFieldRegisterPanel1.add(inputNamaRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, -1));

        inputNoTelpRegister1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputNoTelpRegister1.setLabelText("Nomor Telepon");
        textFieldRegisterPanel1.add(inputNoTelpRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, -1));

        inputAlamatRegister1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputAlamatRegister1.setLabelText("Alamat");
        textFieldRegisterPanel1.add(inputAlamatRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, -1));

        javax.swing.GroupLayout leftRegisterPanel1Layout = new javax.swing.GroupLayout(leftRegisterPanel1);
        leftRegisterPanel1.setLayout(leftRegisterPanel1Layout);
        leftRegisterPanel1Layout.setHorizontalGroup(
            leftRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftRegisterPanel1Layout.createSequentialGroup()
                .addGroup(leftRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftRegisterPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(leftRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldRegisterPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leftRegisterPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(sudahPunyaAkun1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(loginHere1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        leftRegisterPanel1Layout.setVerticalGroup(
            leftRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftRegisterPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(registerTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textFieldRegisterPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sudahPunyaAkun1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginHere1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        illustration3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        illustration3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/illustration/—Pngtree—medical doctor pharmacy illustration vector_4384152.png"))); // NOI18N

        title3.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        title3.setForeground(new java.awt.Color(255, 255, 255));
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Apotek Tumbuh Bersama");

        slogan3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        slogan3.setForeground(new java.awt.Color(255, 255, 255));
        slogan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slogan3.setText("Pelopor Utama Sehat Jiwa Raga");

        javax.swing.GroupLayout rightRegisterPanel1Layout = new javax.swing.GroupLayout(rightRegisterPanel1);
        rightRegisterPanel1.setLayout(rightRegisterPanel1Layout);
        rightRegisterPanel1Layout.setHorizontalGroup(
            rightRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightRegisterPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(rightRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slogan3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(illustration3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        rightRegisterPanel1Layout.setVerticalGroup(
            rightRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightRegisterPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(slogan3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(illustration3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout baseRegisterPanel1Layout = new javax.swing.GroupLayout(baseRegisterPanel1);
        baseRegisterPanel1.setLayout(baseRegisterPanel1Layout);
        baseRegisterPanel1Layout.setHorizontalGroup(
            baseRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseRegisterPanel1Layout.createSequentialGroup()
                .addComponent(leftRegisterPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightRegisterPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        baseRegisterPanel1Layout.setVerticalGroup(
            baseRegisterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftRegisterPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightRegisterPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane1.addTab("registerTab", baseRegisterPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 889, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerHere1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerHere1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerHere1MouseClicked

    private void loginHere1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHere1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginHere1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LRViewTabbedPaneBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LRViewTabbedPaneBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LRViewTabbedPaneBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LRViewTabbedPaneBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LRViewTabbedPaneBackup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panel.LoginRegisterBasePanel baseLoginPanel1;
    private panel.LoginRegisterBasePanel baseRegisterPanel1;
    private javax.swing.JLabel belumPunyaAkun1;
    private javax.swing.JLabel illustration2;
    private javax.swing.JLabel illustration3;
    private swing.component.TextField inputAlamatRegister1;
    private swing.component.TextField inputNamaRegister1;
    private swing.component.TextField inputNoTelpRegister1;
    private swing.component.PasswordField inputPasswordLogin1;
    private swing.component.PasswordField inputPasswordRegister1;
    private swing.component.TextField inputUsernameLogin1;
    private swing.component.TextField inputUsernameRegister1;
    private javax.swing.JPanel leftLoginPanel1;
    private javax.swing.JPanel leftRegisterPanel1;
    private swing.component.Button loginBtn1;
    private javax.swing.JLabel loginHere1;
    private javax.swing.JLabel loginTitle1;
    private swing.component.Button registerBtn1;
    private javax.swing.JLabel registerHere1;
    private javax.swing.JLabel registerTitle1;
    private swing.GradientPanelRight rightLoginPanel1;
    private swing.GradientPanelRight rightRegisterPanel1;
    private javax.swing.JLabel slogan2;
    private javax.swing.JLabel slogan3;
    private javax.swing.JLabel sudahPunyaAkun1;
    private javax.swing.JTabbedPane tabbedPane1;
    private javax.swing.JPanel textFieldLoginPanel1;
    private javax.swing.JPanel textFieldRegisterPanel1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
